### ISSUE TITLE
Support Distributed Tracing

### ISSUE THREAD

**Issue by philkra** [elastic/apm-agent-php#1]
Provide support for distributed tracing, in case an http request with the header `TRACEPARENT` or `ELASTIC-APM-TRACEPARENT` is issued, use the value that must comply W3C trace context, [example](https://www.w3.org/TR/trace-context/#examples-of-http-traceparent-headers).

- [ ] Implement
- [ ] Documentation (including on how manually pass tracing context)

**Comment by science695** [comment]
Not sure if this should be in its own issue, but is there a possibility of also adding the header to the intercepted curl / guzzle outgoing requests? (In addition to handling when traceparent is in the incoming request headers)

I know the RUM / js agent has a config for allowing certain domains to have the header added.
