### ISSUE TITLE
No more src folder in 1.9.1 tar.gz

### ISSUE THREAD

**Issue by doyelese** [elastic/apm-agent-php#1029]
The 1.9.1 tar.gz does not contain a src folder rendering the build from source instructions invalid

https://www.elastic.co/guide/en/apm/agent/php/current/setup.html#build-from-source

**Comment by maclonghorn** [comment]
Looks like this was removed with commit:  13e8b0b28068f0ceb4919eed408870d4ed976188
My builds are now failing.  I'm going to specify the tag:  v1.9.0

**Comment by coding-bunny** [comment]
Ran into the same problem with our docker builds.
Please update the official documentation on how to build from source or fix this.

**Comment by doyelese** [comment]
> > Ran into the same problem with our docker builds. Please update the official documentation on how to build from source or fix this.
> 
> Our commands to get it working if you're interested or stuck
> 
> ```
> COPY apm-agent-php-1.9.1.tar.gz /etc/apm-agent/apm-agent-php-1.9.1.tar.gz
> RUN cd /etc/apm-agent/ \
>     && tar -xf apm-agent-php-1.9.1.tar.gz \
>     && cd apm-agent-php-1.9.1/agent/native/ext \
>     && phpize \
>     && CFLAGS="-std=gnu99" ./configure --enable-elastic_apm \
>     && make clean \
>     && make \
>     && make install
> ```

Actually this doesn't work, we are reverting to previous install method as this will let the `elastic-apm` show up in PHP modules but our elastic application stopped reporting to APM

**Comment by intuibase** [comment]
Hey @doyelese  @maclonghorn @coding-bunny 

I have updated documentation in this [pull request](https://github.com/intuibase/apm-agent-php/commit/fcff029e4c2d33426e62751d5bb39304f555f918)

Can you follow new steps and check if it helped?

Best regards,
Pawel

**Comment by coding-bunny** [comment]
Doesn't seem to work for me.
Our Dockerfile does the following:

```
RUN mkdir -p /home/apm-agent && \
    cd /home/apm-agent && \
    git clone https://github.com/elastic/apm-agent-php.git apm && \
    cd apm && \
    /usr/local/bin/phpize CFLAGS="-std=gnu99" && \
    BUILD_ARCHITECTURE=linux-x86-64 make -f .ci/Makefile build && \
    PHP_CONFIG=php-config sudo cp agent/native/_build/${BUILD_ARCHITECTURE}-release/ext/elastic_apm-`$PHP_CONFIG --phpapi`.so `$PHP_CONFIG --extension-dir`
```

And since i am not familiar with PHP or the tooling used in this case, I don't know what to fix to make this work the way it did before.

**Comment by intuibase** [comment]
Hi @coding-bunny 

The problem with your script is that you need to remove old style build command and keep it like this:
```
RUN mkdir -p /home/apm-agent && \
    cd /home/apm-agent && \
    git clone https://github.com/elastic/apm-agent-php.git apm && \
    cd apm && \
    BUILD_ARCHITECTURE=linux-x86-64 make -f .ci/Makefile build && \
    PHP_CONFIG=php-config sudo cp agent/native/_build/${BUILD_ARCHITECTURE}-release/ext/elastic_apm-`$PHP_CONFIG --phpapi`.so `$PHP_CONFIG --extension-dir`
```

but the problem here is that you're trying to run docker container inside docker container. You can bypass that by mounting docker socker, but it is tricky.

You can build agent on the host you're building your docker image and simply use docker COPY command.

**Comment by alexbaileyuk** [comment]
This has also tripped us up today simply attempting to build for ARM.

Given that we would like to build the extension for ARM using this process, does Elastic provide an ARM version of this image `elasticobservability/apm-agent-php-dev:native-build-gcc-12.2.0-linuxmusl-x86-64-0.0.2`

**Comment by intuibase** [comment]
Hey @alexbaileyuk 


Do you need aarch64v8 Alpine musl or glibc build?

Best regards,
Pawel

**Comment by alexbaileyuk** [comment]
@intuibase Alpine musl version please

**Comment by intuibase** [comment]
@alexbaileyuk you can try building Alpine aarch64 version with laters 1.10.0 release. You can follow https://github.com/intuibase/apm-agent-php/blob/main/DEVELOPMENT.md or just compile it with:
```
## To compile the library for all supported PHP releases for musl libc Linux distributions for aarch64 (ARMv8) architecture. This build is not officially supported.
BUILD_ARCHITECTURE=linuxmusl-arm64 make -f .ci/Makefile build
```

**Comment by alexbaileyuk** [comment]
> @alexbaileyuk you can try building Alpine aarch64 version with laters 1.10.0 release. You can follow https://github.com/intuibase/apm-agent-php/blob/main/DEVELOPMENT.md or just compile it with:
> ```
> ## To compile the library for all supported PHP releases for musl libc Linux distributions for aarch64 (ARMv8) architecture. This build is not officially supported.
> BUILD_ARCHITECTURE=linuxmusl-arm64 make -f .ci/Makefile build
> ```

Thanks. I'll give that a go later this week. Do you ever plan to make it officially supported?

**Comment by intuibase** [comment]
Hey @alexbaileyuk 

We are considering official support for ARM. The problem here is the lack of github support for this architecture.

**Comment by intuibase** [comment]
Hey @doyelese @coding-bunny 

Have you tried building agent in the latest version (v1.10.0) ?

**Comment by coding-bunny** [comment]
I have not, simply not a priority at the moment for us.
Will try to get back to this when I can.
