### ISSUE TITLE
OPTION to disable auto transaction creation

### ISSUE THREAD

**Issue by Legion112** [elastic/apm-agent-php#1035]
**Is your feature request related to a problem? Please describe.**
I wanna user custom transaction creation with naming offered by framework.
There is a way to disable auto transaction creation for HTTP request via `transaction_ignore_urls` but there is no way to do same for cli command.
 

**Describe the solution you'd like**
Would be nice to have a single option that **disables** entirely **auto transaction** creation  like `transaction_auto` which would have default value to `true`

Changes have to be made inside here: 
https://github.com/elastic/apm-agent-php/blob/85b17c07b7a50a30142259788b6e70256effa05d/agent/php/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php#L123-L125
Before executing this method we should check if it is allowed to created transaction automatically via setting (`transaction_auto`)

**Comment by SergeyKleyman** [comment]
You can achieve your goal using public API `ElasticApm::getCurrentTransaction()->discard()`.

**Comment by Legion112** [comment]
No longer interested in this change
