### ISSUE TITLE
Unnamed PHP

### ISSUE THREAD

**Issue by tldale** [elastic/apm-agent-php#104]
Hello,

Even though i named the server in the .ini file placed in /etc/php.d/ it still says unnamed:

; The required service's name to identify it later in the APM UI
; Please change to a to your use case appropiate name.
elastic_apm.service_name = example.domain.com

Thanks!

**Comment by SergeyKleyman** [comment]
Hi @tldale 

Thank you for the feedback - it's very valuable!

Regarding the issue - you are correct, `Unnamed PHP service` is indeed [hardcoded](https://github.com/elastic/apm-agent-php/blob/c1ce2c064bdbe95592a7e5a75623040c818c87bc/src/ElasticApm/Impl/MetadataDiscoverer.php#L42).

I'll merge a fix ASAP.
