### ISSUE TITLE
request cookies must be encoded as a map

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-agent-php#1040]
**Describe the bug**

When sending transactions, request cookies are not marshaled correctly, leading to invalid format and ingestion failure in apm-server.

The following error message was observed in ecs logs:

```
decode error: data read error: v2.transactionRoot.Transaction: v2.transaction.Context: v2.context.Request: v2.contextRequest.Cookies: ReadMapCB: expect { or n,
```

**To Reproduce**

I don't have steps to reproduce, this is part of the ops KPI review and was observed in the ecs logs.

**Expected behavior**

transactions are reported in a valid format and ingestion in apm-server succeed

**Comment by SergeyKleyman** [comment]
HI @kruskall Are you sure this issue occurs with Elastic APM PHP agent? Because so far capturing cookies is not implemented for Elastic APM PHP agent.

**Comment by intuibase** [comment]
We're closing the issue as it is not relevant to PHP agent.
