### ISSUE TITLE
[META 826] changes to `metadata.cloud.project.*` fields collected for GCP

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-php#1053]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/826

**Comment by trentm** [comment]
It looks like the PHP agent doesn't yet collect cloud metadata. There is https://github.com/elastic/apm-agent-php/issues/76 for that, so this issue isn't necessary.
