### ISSUE TITLE
[Packaging] Agent folder structure where the distributions will be installed

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-php#107]
This is regarding the folder structure where the package agent is installed, so far it's defined in:
- https://github.com/elastic/apm-agent-php/blob/f42ad42f28ee55ef051793fb0d382b9d4a1970c4/packaging/post-install.sh#L6
- https://github.com/elastic/apm-agent-php/blob/f42ad42f28ee55ef051793fb0d382b9d4a1970c4/packaging/Makefile#L5
- https://github.com/elastic/apm-agent-php/blob/f42ad42f28ee55ef051793fb0d382b9d4a1970c4/packaging/Makefile#L37-L41

Other PHP plugins/extensions provide the below structure:

- https://packages.debian.org/stretch/all/php-mail/filelist

```
/usr/share/doc/php-mail/changelog.Debian.gz
/usr/share/doc/php-mail/changelog.gz
/usr/share/doc/php-mail/copyright
/usr/share/doc/php-mail/package.xml.gz
/usr/share/php/.registry/mail.reg
/usr/share/php/Mail.php
/usr/share/php/Mail/RFC822.php
```

- https://packages.debian.org/stretch/all/php-horde-service-twitter/filelist

```
/usr/share/doc/php-horde-service-twitter/changelog.Debian.gz
/usr/share/doc/php-horde-service-twitter/changelog.gz
/usr/share/doc/php-horde-service-twitter/copyright
/usr/share/doc/php-horde-service-twitter/examples/twitter_browser.php
/usr/share/doc/php-horde-service-twitter/examples/twitter_cli.php
/usr/share/doc/php-horde-service-twitter/package.xml.gz
/usr/share/php/.registry/.channel.pear.horde.org/horde_service_twitter.reg
/usr/share/php/Horde/Service/Twitter.php
/usr/share/php/Horde/Service/Twitter/Account.php
/usr/share/php/Horde/Service/Twitter/Auth.php
```

So we could potentially use `/usr/share/php/elastic/apm-agent` and `/usr/share/doc/php-elastic-apm-agent/`, what do you think?

**Comment by SergeyKleyman** [comment]
As we discussed, I think we can stay with `/opt/elastic/apm-agent-php` directory since Elastic APM PHP Agent is kind of "optional" software (in the sense that it's just for monitoring and not used in the main part of the monitored applications).
Let's wait for feedback and reconsider the issue if it will be required.

**Comment by SergeyKleyman** [comment]
It's already implemented.
