### ISSUE TITLE
Add export support for opentelemetry-collector

### ISSUE THREAD

**Issue by LHB6540** [elastic/apm-agent-php#1096]
Whether to consider supporting exporting data to opentelemetry-collector. elastic-php-agent is the best php instrumentation I have ever used, but is it possible to export Trace data to opentelemetry-collector?
All visualization work in my organization is now based on Grafana Labs. Grafana's Tempo supports opentelemetry standard data and does not support Elastic APM data.
I noticed that opentelemetry-collector supports exporting opentelemetry data to Elastic APM data, so why not go one step further and support Elastic APM to export data to opentelemetry, giving users more choices.
I'm not sure whether this work should be done by ES or opentelemetry, so I raised the same issues under the opentelemetry-collector repository. Sorry if it caused confusion.

**Comment by SergeyKleyman** [comment]
@LHB6540 Thank you for suggestion. Indeed Elastic's APM is in the process of strategical shift to OpenTelemetry. In particular as part of this new strategy we are working on the new generation of Elastic APM PHP Agent that will be based on OpenTelemetry for PHP and Elastic will contribute all the new work to OpenTelemetry. Of course the new generation of Elastic APM PHP Agent will work with OpenTelemetry collector natively.
