### ISSUE TITLE
Produce root-span ONLY in OLTP format

### ISSUE THREAD

**Issue by intuibase** [elastic/apm-agent-php#1109]
The goal is to produce only the very basic data and clean up code base from unnecessary code.

Provide the name and basic attributes.

Tasks to do:

- [ ] clean up the code, remove implementation and functionality which is not related to root span creation
- [ ] adapt component tests to be able to test only this basic functionality
- [ ] implement root span creation

branch: PHP-OTEL-1

**Comment by SergeyKleyman** [comment]
Replaced by https://github.com/elastic/elastic-otel-php/issues/2
