### ISSUE TITLE
apm-agent-php  versus used extension version.

### ISSUE THREAD

**Issue by hetii** [elastic/apm-agent-php#1112]
Hi.

I use apm-agent-php (1.10.0) and notice that installer use elastic_apm-20210902.so while on storage there is also elastic_apm-20220829.

Is it a bug? Do we need all that different extension in different versions?

![obraz](https://github.com/elastic/apm-agent-php/assets/3405461/a6ccaa50-300c-4be8-bf23-f458949199e9)

![obraz](https://github.com/elastic/apm-agent-php/assets/3405461/9fca0761-0333-4a96-9df7-44402df96c7b)

**Comment by SergeyKleyman** [comment]
@hetii Thank you for opening an issue. Could you please clarify what would you like to achieve? Did the Elastic APM PHP agent installer not work as expected? Is it possible that you added/upgraded PHP version after you installed Elastic APM PHP agent? In that case we recommend to uninstall the agent and install it again - it will automatically detect the current PHP version and reference the correct .so file.
FYI those dates in .so files are what is called "PHP API" version. Usually each PHP major.minor release a different "PHP API" version and require a different .so file for extension. Elastic APM PHP agent installer automatically detects the current PHP version and references the correct .so file.

**Comment by SergeyKleyman** [comment]
Closing it for now - please let us know if it's still relevant.
