### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by brecht-vermeersch** [elastic/apm-agent-php#1114]
Please use the [discuss forum](https://discuss.elastic.co/c/apm) to ask questions.

**Comment by brecht-vermeersch** [comment]
Asking because I see PHP 8.3 is not supported yet

**Comment by intuibase** [comment]
Hey @brecht-vermeersch

Yes it is still maintained. We're supporting PHP 8.3 from the latest [1.13 release](https://github.com/elastic/apm-agent-php/releases/tag/v1.13.0). Please try it out and share you feedback.

Regards,
Pawel
