### ISSUE TITLE
502 error when used with ionCube loader

### ISSUE THREAD

**Issue by belkone** [elastic/apm-agent-php#123]
Is it possible to use this together with ionCube loader?

The agent doesn't work when I turn on `zend_extension = ioncube_loader_lin_7.2.so` in php.ini.
It is enough that the module is loaded in php.ini, tested service does not have to use ionCube to cause an error (doesn't work even with a pure php script)
Extensions loading order does not matter.

I haven't found any logs related to this case, is it possible to enable debug logs for this?
PHP 7.2 (fpm)

**Comment by SergeyKleyman** [comment]
Could you please provide Agent logs sent to syslog?

**Comment by belkone** [comment]
> Could you please provide Agent logs sent to syslog?

Sure, here: https://pastebin.com/p2B9Kv9B

**Comment by belkone** [comment]
> Could you please provide Agent logs sent to syslog?

Sure, here: https://pastebin.com/AMxem6YB

**Comment by SergeyKleyman** [comment]
```
Aug 20 11:02:36 test ool www: Elastic APM PHP Tracer [PID: 29658] 2020-08-20 11:02:36.471810+02:00 [DEBUG]    [C-to-PHP] [tracer_PHP_part.c:30] [bootstrapTracerPhpPart] Entered: config->bootstrapPhpPartFile: `/var/www/apm-agent-php/src/bootstrap_php_part.php'
Aug 20 11:02:36 test ool www: Elastic APM PHP Tracer [PID: 29658] 2020-08-20 11:02:36.471823+02:00 [DEBUG]    [Util] [util_for_PHP.c:27] [loadPhpFile] Entered: filename: `/var/www/apm-agent-php/src/bootstrap_php_part.php'
Aug 20 11:02:39 test systemd[1]: Stopping The PHP 7.2 FastCGI Process Manager...
```
It seems that C part (.so extension) of the agent cannot load PHP part (`/var/www/apm-agent-php/src/bootstrap_php_part.php`). 

1. Is the path `/var/www/apm-agent-php/src/bootstrap_php_part.php` correct?
2. Is it possible that the user under which fpm worker is running doesn't have permissions to access `/var/www/apm-agent-php/src/bootstrap_php_part.php`?

**Comment by belkone** [comment]
> ```
> Aug 20 11:02:36 test ool www: Elastic APM PHP Tracer [PID: 29658] 2020-08-20 11:02:36.471810+02:00 [DEBUG]    [C-to-PHP] [tracer_PHP_part.c:30] [bootstrapTracerPhpPart] Entered: config->bootstrapPhpPartFile: `/var/www/apm-agent-php/src/bootstrap_php_part.php'
> Aug 20 11:02:36 test ool www: Elastic APM PHP Tracer [PID: 29658] 2020-08-20 11:02:36.471823+02:00 [DEBUG]    [Util] [util_for_PHP.c:27] [loadPhpFile] Entered: filename: `/var/www/apm-agent-php/src/bootstrap_php_part.php'
> Aug 20 11:02:39 test systemd[1]: Stopping The PHP 7.2 FastCGI Process Manager...
> ```
> 
> 
> It seems that C part (.so extension) of the agent cannot load PHP part (`/var/www/apm-agent-php/src/bootstrap_php_part.php`).
> 
> 
> 
> 1. Is the path `/var/www/apm-agent-php/src/bootstrap_php_part.php` correct?
> 
> 2. Is it possible that the user under which fpm worker is running doesn't have permissions to access `/var/www/apm-agent-php/src/bootstrap_php_part.php`?

1. yes
2. user has got right permissions, because if I unload the ioncube .so extension , the agent starts working properly - they just can't be loaded together.

**Comment by SergeyKleyman** [comment]
I took a look on what ioncube does and I agree with you that the root cause is ioncube clashing with agent's loading of its PHP part.
Does ioncube have configuration where you can exclude certain code sources from its protection?

**Comment by belkone** [comment]
I don't think anything can be configured on the ioncube loader side, it works like "turn it on and forget it".
Maybe something can be done on the side of the apm agent?

**Comment by SergeyKleyman** [comment]
I googled `ioncube PHP APM` and names of other vendors that have PHP APM solutions and it seems that ionCUBE Loader is not supported by those vendors neither.
Maybe the deployment approach described in https://github.com/elastic/apm-agent-php/issues/119 can be used with ionCUBE Loader but that approach will not include automatic capture of transaction and spans - it will require application/library developers to use [agent's public API](https://github.com/elastic/apm-agent-php/blob/master/docs/public-api.asciidoc). If it's something that you think might work for you please leave a comment at https://github.com/elastic/apm-agent-php/issues/119. We will take users demand into account when we prioritize that issue but I cannot promise we will implement it in the near future. Of course the community can contribute implementation for that issue as well - you are welcome if you would like to give a try.

**Comment by belkone** [comment]
OK thanks for the information. I will look at this problem again and maybe I can find a solution - then I will let you know :)
