### ISSUE TITLE
Can't make apm-agent-php

### ISSUE THREAD

**Issue by laokiea** [elastic/apm-agent-php#124]
hi,
i try install apm-agent-php. but I get an error during installation
![image](https://user-images.githubusercontent.com/13516246/90129270-ea126e80-dd9a-11ea-9056-203dbc463970.png)

Os: Ubuntu 14.04.6 LTS
PHP version: PHP 7.1.33

**Comment by SergeyKleyman** [comment]
Hi @laokiea ,

Thank you for the feedback - it's very valuable!

Regarding the issue - we support PHP 7.2 and higher. I'm not 100% sure that this is the actual reason behind your particular compilation error but it's quite possible.
I'll also make sure we clearly state which PHP versions we support.

**Comment by laokiea** [comment]
> Hi @laokiea ,
> 
> Thank you for the feedback - it's very valuable!
> 
> Regarding the issue - we support PHP versions 7.2-7.4. I'm not 100% sure that this is the actual reason behind your particular compilation error but it's quite possible.
> I'll also make sure we clearly state which PHP versions we support.

Thank you for your reply. I upgrade PHP to version 7.4. The installation was successful.
