### ISSUE TITLE
Configuration option: ENVIRONMENT

### ISSUE THREAD

**Issue by laokiea** [elastic/apm-agent-php#125]
How can i configure `environment` option, Is there a configuration option named `elastic_apm.environment`

**Comment by SergeyKleyman** [comment]
PHP Agent doesn't support `ENVIRONMENT` configuration option yet but it should a very low effort to add it so I'll prioritize to do it ASAP.

**Comment by laokiea** [comment]
> PHP Agent doesn't support `ENVIRONMENT` configuration option yet but it should very low effort to add it so I'll prioritize to do it ASAP

Hi: 
Thank you for your reply, The name of `ENVIRONMENT` configuration option is`elastic_apm.environment`?

**Comment by SergeyKleyman** [comment]
> The name of `ENVIRONMENT` configuration option is`elastic_apm.environment`?

Yes, all the options are named `elastic_apm.<option name lower case>` in `php.ini` and `ELASTIC_APM_<OPTION NAME UPPER CASE>` as environment variable (`php.ini` has higher priority).

I'll add a paragraph clarifying that at docs/configuration.asciidoc and specific `php.ini` key and environment variable name for each supported option.

**Comment by laokiea** [comment]
> > The name of `ENVIRONMENT` configuration option is`elastic_apm.environment`?
> 
> Yes, all the options are named `elastic_apm.<option name lower case>` in `php.ini` and `ELASTIC_APM_<OPTION NAME UPPER CASE>` as environment variable (`php.ini` has higher priority).
> 
> I'll add a paragraph clarifying that at docs/configuration.asciidoc and specific `php.ini` key and environment variable name for each supported option.

Hi:
I have reinstalled `apm-agent-php` and configured `ENVIRONMENT` option as `elastic_apm.environment` in `php.ini` but it doesn't work.

**Comment by SergeyKleyman** [comment]
Which version of APM Server do you use?

**Comment by laokiea** [comment]
> Which version of APM Server do you use?
I refreshed the panel, and It works now.
