### ISSUE TITLE
Automatically create spans for DB operations

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#13]

**Comment by science695** [comment]
Is it in the plan to detect the DB type and choose a subtype other than sqlite? https://github.com/elastic/apm-agent-php/blob/master/src/ElasticApm/Impl/AutoInstrument/PdoAutoInstrumentation.php#L48

I see the constants are commented out for other subtypes: https://github.com/elastic/apm-agent-php/blob/master/src/ElasticApm/Impl/Constants.php#L24

**Comment by SergeyKleyman** [comment]
@science695 First of all, thank you for interest in improving the agent.

To answer your question - yes, the goal is definitely to detect actual DB type automatically. As you can see current state of auto-instrumentation is bare minimum - just to test PHP extension hooks correctness. This issue is to improve that area and collect all the necessary data.

Regarding the possible implementation - I didn't think about it that much but I assumed that DB type will have to be extracted by parsing the connection string. Do you think there are alternative approaches?

**Comment by science695** [comment]
Yes, I am very excited at even the bare minimum that is here already. And I understand this is in-progress.

I haven't done a ton with other DB types, but my understanding is that the connection string contains the driver identifier, and that may not always be a 1-1 relationship to DB type (generic drivers that can connect to multiple formats, ODBC, etc...). 

Driver list just for reference: https://www.php.net/manual/en/pdo.drivers.php

It did bring up some questions like:
- Is the DB type as useful if you have the host already?
- Is just the driver name as useful as which type?
- Should there be a way to supplement the auto-instrumenting with some help from the application (a method to call to hint the dbtype, or other attributes that may be hard to detect, or may detect incorrectly)

**Comment by SergeyKleyman** [comment]
> - Is the DB type as useful if you have the host already?
> - Is just the driver name as useful as which type?

Since DB type sent by the agent is just a keyword stored in Elasticsearch we can start with putting driver identifier as DB type if it's not clear how to extract DB type from driver identifier. Based on feedback from user when can changed it later.

> Should there be a way to supplement the auto-instrumenting with some help from the application (a method to call to hint the dbtype, or other attributes that may be hard to detect, or may detect incorrectly)

The planned approach is two pronged:
1. Creating events manually: The same API that used by auto-instrumentation part of the agent is available to the application developer so it's possible to create events (transactions, spans, etc.) manually in exactly the same way as auto-instrumentation part does it.
2. Changing already created events: Similarly to other Elastic APM Agents ([for example .NET Agent](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#filter-api)) it will possible to register a callable to modify/discard automatically/manually created events. I've added https://github.com/elastic/apm-agent-php/issues/67 to follow up. Will it address your use case?

**Comment by science695** [comment]
That looks quite elegant. Yeah, that should give all the flexibility you would need.

**Comment by SergeyKleyman** [comment]
The feature itself is already implemented. Automated testing part is split to a separate issue - #246
