### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by tumenzul** [elastic/apm-agent-php#147]
OS: CentOS Linux release 7.8.2003 (Core)
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

Following error occurred during compile.
`In file included from /home/docker/elastic-apm/apm-agent-php/src/ext/ConfigManager.h:23:0,
                 from /home/docker/elastic-apm/apm-agent-php/src/ext/ConfigManager.c:12:
/home/docker/elastic-apm/apm-agent-php/src/ext/util.h: In function 'replaceCharInString':
/home/docker/elastic-apm/apm-agent-php/src/ext/util.h:44:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for ( size_t i = 0 ; str[ i ] != '\0' ; ++i )
     ^
/home/docker/elastic-apm/apm-agent-php/src/ext/util.h:44:5: note: use option -std=c99 or -std=gnu99 to compile your code
/home/docker/elastic-apm/apm-agent-php/src/ext/util.h: In function 'replaceCharInStringView':
/home/docker/elastic-apm/apm-agent-php/src/ext/util.h:53:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for ( size_t i = 0 ; i != strView.length ; ++i )
     ^
In file included from /home/docker/elastic-apm/apm-agent-php/src/ext/util.h:21:0,
                 from /home/docker/elastic-apm/apm-agent-php/src/ext/ConfigManager.h:23,
                 from /home/docker/elastic-apm/apm-agent-php/src/ext/ConfigManager.c:12:
/home/docker/elastic-apm/apm-agent-php/src/ext/util.h: In function 'isStringViewPrefixIgnoringCase':
/home/docker/elastic-apm/apm-agent-php/src/ext/basic_macros.h:27:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for ( indexVarType indexVar = rangeStart ; (indexVar) < (rangeExcludedEnd) ; ++indexVar )
`
Then googling this issue, I am added -std=c99 flag. 
Now it giving other errors 

`In file included from /home/docker/elastic-apm/apm-agent-php/src/ext/elastic_apm_API.c:18:0:
/home/docker/elastic-apm/apm-agent-php/src/ext/numbered_intercepting_callbacks.h:1039:1: error: unknown type name 'zif_handler'
 static zif_handler g_numberedInterceptingCallback[ numberedInterceptingCallbacksCount ] =
 ^
/home/docker/elastic-apm/apm-agent-php/src/ext/numbered_intercepting_callbacks.h:1041:17: warning: initialization makes integer from pointer without a cast [enabled by default]
                 [ 0 ] = ELASTIC_APM_NUMBERED_INTERCEPTING_CALLBACK_NAME( 0 ),
                 ^
/home/docker/elastic-apm/apm-agent-php/src/ext/numbered_intercepting_callbacks.h:1041:17: warning: (near initialization for 'g_numberedInterceptingCallback[0]') [enabled by default]
/home/docker/elastic-apm/apm-agent-php/src/ext/numbered_intercepting_callbacks.h:1041:17: error: initializer element is not computable at load time
/home/docker/elastic-apm/apm-agent-php/src/ext/numbered_intercepting_callbacks.h:1041:17: error: (near initialization for 'g_numberedInterceptingCallback[0]')
/home/docker/elastic-apm/apm-agent-php/src/ext/numbered_intercepting_callbacks.h:1042:17: warning: initialization makes integer from pointer without a cast [enabled by default]
                 [ 1 ] = ELASTIC_APM_NUMBERED_INTERCEPTING_CALLBACK_NAME( 1 ),
                 ^
/home/docker/elastic-apm/apm-agent-php/src/ext/numbered_intercepting_callbacks.h:1042:17: warning: (near initialization for 'g_numberedInterceptingCallback[1]') [enabled by default]
/home/docker/elastic-apm/apm-agent-php/src/ext/numbered_intercepting_callbacks.h:1042:17: error: initializer element is not computable at load time
/home/docker/elastic-apm/apm-agent-php/src/ext/numbered_intercepting_callbacks.h:1042:17: error: (near initialization for 'g_numberedInterceptingCallback[1]')
/home/docker/elastic-apm/apm-agent-php/src/ext/numbered_intercepting_callbacks.h:1043:17: warning: initialization makes integer from pointer without a cast [enabled by default]
                 [ 2 ] = ELASTIC_APM_NUMBERED_INTERCEPTING_CALLBACK_NAME( 2 ),
`

**Comment by SergeyKleyman** [comment]
I saw that you posted this question at https://discuss.elastic.co/t/php-agent-compilation-error/245732 as well - If you don't mind I propose to use discuss for further discussion :) I've posted a suggestion there. Please take a look.

**Comment by SergeyKleyman** [comment]
It seems that the issue is the same as in https://github.com/elastic/apm-agent-php/issues/124. I've opened to https://github.com/elastic/apm-agent-php/pull/149 to document which PHP version are supported.

**Comment by tumenzul** [comment]
I've upgraded PHP version to 7.3.19 and now it is giving following error

`/bin/sh /root/Downloads/apm-agent-php-master/src/ext/libtool --mode=compile gcc  -I. -I/root/Downloads/apm-agent-php-master/src/ext -DPHP_ATOM_INC -I/root/Downloads/apm-agent-php-master/src/ext/include -I/root/Downloads/apm-agent-php-master/src/ext/main -I/root/Downloads/apm-agent-php-master/src/ext -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -std=c99   -c /root/Downloads/apm-agent-php-master/src/ext/elastic_apm_assert.c -o elastic_apm_assert.lo
libtool: compile:  gcc -I. -I/root/Downloads/apm-agent-php-master/src/ext -DPHP_ATOM_INC -I/root/Downloads/apm-agent-php-master/src/ext/include -I/root/Downloads/apm-agent-php-master/src/ext/main -I/root/Downloads/apm-agent-php-master/src/ext -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -std=c99 -c /root/Downloads/apm-agent-php-master/src/ext/elastic_apm_assert.c  -fPIC -DPIC -o .libs/elastic_apm_assert.o
In file included from /usr/include/php/Zend/zend.h:40:0,
                 from /usr/include/php/main/php.h:33,
                 from /root/Downloads/apm-agent-php-master/src/ext/ConfigManager.h:18,
                 from /root/Downloads/apm-agent-php-master/src/ext/elastic_apm_assert.c:14:
/usr/include/php/Zend/zend_signal.h:46:2: error: unknown type name âsiginfo_tâ
  siginfo_t *siginfo;
  ^
In file included from /usr/include/php/Zend/zend.h:40:0,
                 from /usr/include/php/main/php.h:33,
                 from /root/Downloads/apm-agent-php-master/src/ext/ConfigManager.h:18,
                 from /root/Downloads/apm-agent-php-master/src/ext/elastic_apm_assert.c:14:
/usr/include/php/Zend/zend_signal.h:95:76: warning: âstruct sigactionâ declared inside parameter list [enabled by default]
 ZEND_API int zend_sigaction(int signo, const struct sigaction *act, struct sigaction *oldact);
                                                                            ^
/usr/include/php/Zend/zend_signal.h:95:76: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
In file included from /root/Downloads/apm-agent-php-master/src/ext/util.h:25:0,
                 from /root/Downloads/apm-agent-php-master/src/ext/ConfigManager.h:23,
                 from /root/Downloads/apm-agent-php-master/src/ext/elastic_apm_assert.c:14:
/root/Downloads/apm-agent-php-master/src/ext/elastic_apm_clock.h: In function âconvertUtcToLocalTimeDefaultImplâ:
/root/Downloads/apm-agent-php-master/src/ext/elastic_apm_clock.h:57:12: warning: implicit declaration of function âlocaltime_râ [-Wimplicit-function-declaration]
     struct tm* localtimeRetVal = localtime_r( &input, &outputLocal );
            ^
/root/Downloads/apm-agent-php-master/src/ext/elastic_apm_clock.h:57:34: warning: initialization makes pointer from integer without a cast [enabled by default]
     struct tm* localtimeRetVal = localtime_r( &input, &outputLocal );
                                  ^
/root/Downloads/apm-agent-php-master/src/ext/elastic_apm_clock.h:62:39: error: âstruct tmâ has no member named âtm_gmtoffâ
     secondsAheadUtcLocal = outputLocal.tm_gmtoff;
                                       ^
make: *** [elastic_apm_assert.lo] Error 1
`

**Comment by SergeyKleyman** [comment]
Please try steps at https://github.com/elastic/apm-agent-php/issues/97#issuecomment-662265015
If it resolves the issue for you I'll see if we can make `gnu99` to be the default for `gcc` when building the agent.

**Comment by SergeyKleyman** [comment]
Also I would recommend running `make clean` before re-running the steps in [the documentation](https://github.com/elastic/apm-agent-php/blob/master/docs/setup.asciidoc) - to rule out the possibility that something was left over from the previous run.

**Comment by tumenzul** [comment]
I am adding following flags to compile. It finished without error.
`CFLAGS="-O3 -std=gnu99 -ffast-math -march=native"`

Thank you
