### ISSUE TITLE
Automatically created HTTP spans should fit the spec

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#151]
Currently, as part of `curl` automatic instrumentation, we automatically create HTTP spans (by instrumenting `curl_exec`) but these spans do not satisfy [the current spec](https://github.com/elastic/apm/blob/d8cb5607dbfffea819ab5efc9b0743044772fb23/specs/agents/tracing-instrumentation-http.md#http-client-spans).

- [ ] Span name should have the format `<method> <host>`
- Context
    - [ ] `http.url` (the target URL)
    - [ ] `http.status_code` (the response status code)

**Comment by SergeyKleyman** [comment]
> Is there any possibility of being able to customize the instrumented span name?

Yes, we definitely would like to allow modifying automatically created events. We plan to support in the same way as I mentioned in [this comment](https://github.com/elastic/apm-agent-php/issues/13#issuecomment-651530459).

**Comment by aguimaraes** [comment]
> 

The filtering feature is fantastic; looking forward to it.

I have a suggestion for this specific requirement.

Wouldn't it be simpler and resource-efficient to configure the schema for the name of the HTTP request span via php.ini param or an environment variable? e.g.: [url groups](https://www.elastic.co/guide/en/apm/agent/php/current/configuration-reference.html#config-url-groups)

Executing a function every single time to change a schema that can be defined once by config looks wasteful.
