### ISSUE TITLE
[RELEASE] Upload artifacts to the official elastic repos if possible

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-php#196]
### What

Upload artifacts to https://artifacts.elastic.co/packages

### Why

This will help to have the same user experience regarding the installation process for the php agent.

On the other hand, we can use the download analytics.

### Actions

- [x] Contact the Unified release team regarding this

**Comment by SergeyKleyman** [comment]
Closing because it does not seem that publishing releases at https://artifacts.elastic.co/ is a priority.
