### ISSUE TITLE
Add the support of socket connection using libcurl

### ISSUE THREAD

**Issue by ezimuel** [elastic/apm-agent-php#21]
Since we want to support socket connection for communicate with APM server, we need to add it to CURL connection.
We want to give the possibility to specify a URL string in `elasticapm.host` using `http:` (or `https:`) and a socket connection using `unix:` prefix.

**Comment by SergeyKleyman** [comment]
Since we are not sure if we are going to implement it we are closing it for now and we will revisit it later if necessary.
