### ISSUE TITLE
Add public API to set user information

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#238]
Relevant part of APM Server Intake API: https://github.com/elastic/apm-server/blob/7.0/docs/spec/user.json
`user.json` is referenced in https://github.com/elastic/apm-server/blob/7.0/docs/spec/context.json#L49 which the context kind used transactions and errors but not spans (AKA "transaction" context).

Derived from: https://discuss.elastic.co/t/how-add-user-info-into-transaction/252474

**Comment by petericebear** [comment]
For Laravel: https://laravel.com/docs/9.x/authentication#retrieving-the-authenticated-user

**Comment by SergeyKleyman** [comment]
Implemented in #758
