### ISSUE TITLE
PHP errors are not reported as APM error events

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-php#300]
**Describe the bug**

Is error reporting working for the PHP Agent Beta?  

I ask because I was able to install the agent and get transactions reporting into an Elastic Cloud instance (yay).  However, errors were _not_ being reported in.

**To Reproduce**

1. Create a same program on your PHP Enabled webserer, as defined below
1. Confirm the fatal and notice level errors
2. Install the Elastic Agent via the .deb file and configure credentials via an `ini` file
3. Restart your web server/php-process to enable the agent
4. Reload the page and reproduce the errors
5. Change the call to the `add` function to `add(2,2)` to remove the fatal error
6. Reload the page and confirm the notice level error remains

**Expected behavior**
Errors are available in your elastic/kibana instance

**Actual behavior**
No errors appears in your elastic/kibana instance

Here's the program mentioned above

```
<?php
ini_set('display_errors','1');
function add($one, $two) {
    return $one + $two;
}

function main($argv) {
    echo add(2);
}
main($notDefined);
```

and a screencap of the errors

![Screen Shot 2020-11-19 at 10 34 50 AM](https://user-images.githubusercontent.com/184372/99708638-f3267200-2a52-11eb-9eb5-1f889cd051bc.png)

Also, attaching a `phpinfo()` page from the server.  [info.zip](https://github.com/elastic/apm-agent-php/files/5568944/info.zip)

**Comment by nhadsall** [comment]
I see this was closed, but not actually working?

**Comment by sherlockliu** [comment]
I encounter this issue on my project, anyone knows how to solve this?

**Comment by RichardLagerstrom** [comment]
> I encounter this issue on my project, anyone knows how to solve this?

See https://github.com/elastic/apm-agent-php/issues/409
