### ISSUE TITLE
.deb Installer (and others) Should Create XX-elastic.ini files for Apache and PHP-FPM

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-php#301]
**Is your feature request related to a problem? Please describe.**

After installing the PHP Agent via `dpkg` and the `deb` file, the installer appended the following 

```
; List of headers files to preload, wildcard patterns allowed.
;ffi.preload=
; THIS IS AN AUTO-GENERATED FILE by the Elastic PHP agent post-install.sh script
extension=/opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so
elastic_apm.bootstrap_php_part_file=/opt/elastic/apm-agent-php/src/bootstrap_php_part.php
; END OF AUTO-GENERATED by the Elastic PHP agent post-install.sh script
```

to my `/etc/php/7.4/cli/php.ini` ini file.  However, no ini settings were made available for my web server in `/etc/php/7.4/apache2/` or FastCGI server `/etc/php/7.4/fpm/`.  This left me to manually configure these entries.

**Describe the solution you'd like**

It would be better if the elastic installer(s) behaved like other PHP Extension installers and 

1. Created its own `XX-elastic.ini` file rather than append to the existing `php.ini` file
2. Created `ini` files for each PHP SAPI (CLI, FPM, etc) installed on the system

This would both be what a PHP Engineer/DevOps human would expect, and it would better enable them to have automated deployments of their systems. 

**Describe alternatives you've considered**
Manually copying ini files and then forgetting about them when it came time to redeploy PHP on a new server.  Much sadness usually ensues. 

**Additional context**

My PHP Packages came from https://deb.sury.org/, which is the defacto location for up to date versions of PHP on linux.

**Comment by v1v** [comment]
I'll work on this particular issue but tackle it in three different tasks:

- Support for ini files
- Support for Apache
- Support for fpm

**Comment by SergeyKleyman** [comment]
Closed by https://github.com/elastic/apm-agent-php/pull/324
