### ISSUE TITLE
build on mac has error

### ISSUE THREAD

**Issue by roboticsexpert** [elastic/apm-agent-php#308]
**Describe the bug**
when you want to build ext on mac os, it has error:

`

> ➜  ext make
> /bin/ksh /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/libtool --mode=compile cc  -I. -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -DPHP_ATOM_INC -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/include -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/main -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -I/usr/local/Cellar/php/7.4.9/include/php -I/usr/local/Cellar/php/7.4.9/include/php/main -I/usr/local/Cellar/php/7.4.9/include/php/TSRM -I/usr/local/Cellar/php/7.4.9/include/php/Zend -I/usr/local/Cellar/php/7.4.9/include/php/ext -I/usr/local/Cellar/php/7.4.9/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/backend_comm.c -o backend_comm.lo
> mkdir .libs
>  cc -I. -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -DPHP_ATOM_INC -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/include -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/main -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -I/usr/local/Cellar/php/7.4.9/include/php -I/usr/local/Cellar/php/7.4.9/include/php/main -I/usr/local/Cellar/php/7.4.9/include/php/TSRM -I/usr/local/Cellar/php/7.4.9/include/php/Zend -I/usr/local/Cellar/php/7.4.9/include/php/ext -I/usr/local/Cellar/php/7.4.9/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/backend_comm.c  -fno-common -DPIC -o .libs/backend_comm.o
> /bin/ksh /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/libtool --mode=compile cc  -I. -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -DPHP_ATOM_INC -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/include -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/main -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -I/usr/local/Cellar/php/7.4.9/include/php -I/usr/local/Cellar/php/7.4.9/include/php/main -I/usr/local/Cellar/php/7.4.9/include/php/TSRM -I/usr/local/Cellar/php/7.4.9/include/php/Zend -I/usr/local/Cellar/php/7.4.9/include/php/ext -I/usr/local/Cellar/php/7.4.9/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/ConfigManager.c -o ConfigManager.lo
>  cc -I. -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -DPHP_ATOM_INC -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/include -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/main -I/Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext -I/usr/local/Cellar/php/7.4.9/include/php -I/usr/local/Cellar/php/7.4.9/include/php/main -I/usr/local/Cellar/php/7.4.9/include/php/TSRM -I/usr/local/Cellar/php/7.4.9/include/php/Zend -I/usr/local/Cellar/php/7.4.9/include/php/ext -I/usr/local/Cellar/php/7.4.9/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/ConfigManager.c  -fno-common -DPIC -o .libs/ConfigManager.o
> In file included from /Users/roboticsexpert/Projects/apm/apm-agent-php/src/ext/ConfigManager.c:25:
> In file included from ./elastic_apm_alloc.h:20:
> ./platform.h:15:13: fatal error: 'features.h' file not found
> \#   include <features.h>
>             ^~~~~~~~~~~~
> 1 error generated.
> make: *** [ConfigManager.lo] Error 1
> 

**To Reproduce**
1. get mac os big sur
2. then install php 7.4
3. then try to make package

**Expected behavior**
it should build :)

**Comment by phumberdroz** [comment]
Same happens on macos Catalina

**Comment by laokiea** [comment]
I have same error, how to fix it

**Comment by SergeyKleyman** [comment]
It seems `features.h` doesn't exist on MacOS C building environment. [At the moment the agent doesn't support MacOS](https://www.elastic.co/guide/en/apm/agent/php/current/supported-technologies.html). I've created a PR (#398) where I tried to fix this build issue but I'll need somebody to try it out (i.e., building the agent and testing it on MacOS) because I don't have MacOS environment.

**Comment by SergeyKleyman** [comment]
It seems there's no more interest in this issue so I have closed it. We can always re-open it in the future.

**Comment by phumberdroz** [comment]
@SergeyKleyman it seems you have gotten feedback in the Pull Request. I would love to see this happen as currently we have to maintain a wrapper around elastic apm to not "break" our projects running on the developer machines.

**Comment by dangoscomb** [comment]
I have managed to get this to build on Mac but like Windows it just fakes data currently. I will see what I can do when I get 30 minutes to get it working properly with real data.

**Comment by SergeyKleyman** [comment]
> @SergeyKleyman it seems you have gotten feedback in the Pull Request

@dangoscomb I'm sorry I missed that. I've re-opened the issue to keep in mind that it's active.

**Comment by dangoscomb** [comment]
https://github.com/dangoscomb/apm-agent-php/tree/osx-build

The above will build, as mentioned. I have not yet tested it actually running. It should be possible to get CPU and memory data natively but I haven't looked at how yet.

**Comment by SergeyKleyman** [comment]
I'm going to close this issue. Please re-open it if you feel that there are some aspects of this issue that are not addressed yet.
