### ISSUE TITLE
Problem to install agent PHP 7.0

### ISSUE THREAD

**Issue by KelvinFerraz** [elastic/apm-agent-php#364]
Hello,

I tryed install an agent on my Linux using a native package and receive this problem:

```
(Reading database ... 445629 files and directories currently installed.)
Preparing to unpack apm-agent-php_1.0.0-beta1_all.deb ...
Uninstalling Elastic PHP agent
  extension configuration does not exist for the Elastic PHP agent.
  skipping ... 
Extension has been removed successfully for Elastic PHP agent.
Unpacking apm-agent-php (1.0.0-beta1) over (1.0.0-beta1) ...
Setting up apm-agent-php (1.0.0-beta1) ...
Installing Elastic PHP agent
Failed. Elastic PHP agent extension not supported for the current PHP API version.
    PHP API => 20200930
Failed. Elastic PHP agent extension is not enabled
Set up the Agent manually as explained in:
https://github.com/elastic/apm-agent-php/blob/master/docs/setup.asciidoc

```

My PHP is version 7.0

I try to install from the source and receive this problem:

```
                                          ^
In file included from /tmp/apm-agent-php/src/ext/StringView.h:24:0,
                 from /tmp/apm-agent-php/src/ext/elastic_apm_API.h:25,
                 from /tmp/apm-agent-php/src/ext/elastic_apm_API.c:20:
/tmp/apm-agent-php/src/ext/elastic_apm_API.c: In function 'elasticApmCallInterceptedOriginal':
/tmp/apm-agent-php/src/ext/elastic_apm_API.c:221:68: warning: comparison between pointer and integer
     ELASTIC_APM_ASSERT( g_interceptedCallInProgressOriginalHandler != NULL, "" );
                                                                    ^
/tmp/apm-agent-php/src/ext/elastic_apm_assert.h:108:56: note: in definition of macro 'ELASTIC_APM_ASSERT_WITH_LEVEL'
         if ( getGlobalAssertLevel() >= (level) && ( ! (cond) ) ) \
                                                        ^
/tmp/apm-agent-php/src/ext/elastic_apm_API.c:221:5: note: in expansion of macro 'ELASTIC_APM_ASSERT'
     ELASTIC_APM_ASSERT( g_interceptedCallInProgressOriginalHandler != NULL, "" );
     ^
/tmp/apm-agent-php/src/ext/elastic_apm_API.c:223:5: error: called object 'g_interceptedCallInProgressOriginalHandler' is not a function or function pointer
     g_interceptedCallInProgressOriginalHandler( g_interceptedCallInProgressZendExecuteData, return_value );
     ^
/tmp/apm-agent-php/src/ext/elastic_apm_API.c:73:20: note: declared here
 static zif_handler g_interceptedCallInProgressOriginalHandler = NULL;
                    ^
Makefile:217: recipe for target 'elastic_apm_API.lo' failed
make: *** [elastic_apm_API.lo] Error 1
```

To agent, run need a version of PHP more recently?

**Comment by SergeyKleyman** [comment]
Hi @KelvinFerraz - thank you for your feedback.

Judging by `PHP API => 20200930` it seems your PHP version is 8.0 (https://github.com/php/php-src/blob/php-8.0.0/main/php.h).
At the moment Elastic APM PHP agent [supports PHP versions 7.2-7.4](https://www.elastic.co/guide/en/apm/agent/php/current/supported-technologies.html) so I would recommend using PHP 7.4.
We do plan to add support for PHP version 8.0 in the near future - you can subscribe to https://github.com/elastic/apm-agent-php/issues/365 to get notified.

**Comment by KelvinFerraz** [comment]
> Hi @KelvinFerraz - thank you for your feedback.
> 
> Judging by `PHP API => 20200930` it seems your PHP version is 8.0 (https://github.com/php/php-src/blob/php-8.0.0/main/php.h).
> At the moment Elastic APM PHP agent [supports PHP versions 7.2-7.4](https://www.elastic.co/guide/en/apm/agent/php/current/supported-technologies.html) so I would recommend using PHP 7.4.
> We do plan to add support for PHP version 8.0 in the near future - you can subscribe to #365 to get notified.

Thank you @SergeyKleyman, 

I'm sorry I had version 8, but in fact my application works on PHP 7.0. I tried to install with the package but it also didn't work, the agent for PHP doesn't work below 7.2?

**Comment by SergeyKleyman** [comment]
> the agent for PHP doesn't work below 7.2?

Yes, at the moment [the agent supports PHP versions 7.2-7.4](https://www.elastic.co/guide/en/apm/agent/php/current/supported-technologies.html#supported-php-versions).

**Comment by SergeyKleyman** [comment]
I'm going to close this issue. Please re-open it if you feel that there are some aspects of this issue that are not addressed yet.
