### ISSUE TITLE
Add support for PHP 8.0

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#365]
[PHP 8.0 was released on 26 Nov 2020](https://www.php.net/supported-versions.php).

**Comment by rs-ubaldi** [comment]
Hi, could you please give us an estimate when support for PHP 8 can/will be implemented ? We are evaluating the Elastic solution at corporate level and this is a major drawback in our decision matrix. Thanks

**Comment by cyrille-leclerc** [comment]
Hello @rs-ubaldi thank you for your interest in our product.
As you can see with the milestone "7.13" associated with this issue, it's the next task we want to tackle and we want to ship it by the summer.
We will hopefully create a Pull Request soon, it will help tracking progress on this improvement.
We hope this convince you and your organisation that we will support PHP 8 soon.

**Comment by Bilanda** [comment]
Hi, do you have any news concerning support for PHP8 ? I just saw that it's now included in milestone 7.14, we really need this support at corporate level too. Exactly as rs-ubaldi, we are evaluating the elastic solution, and web analysis for our php products are a must have, we are convinced that it will fit our needs, but the php8 support is very important for us. Thanks in advance

**Comment by SergeyKleyman** [comment]
PHP 8 support is already merged into master and it will be included in the next release.

**Comment by SergeyKleyman** [comment]
[FYI v1.1 release contains support for PHP 8](https://github.com/elastic/apm-agent-php/releases/tag/v1.1)
