### ISSUE TITLE
How do I ignore urls?

### ISSUE THREAD

**Issue by mikkeschiren** [elastic/apm-agent-php#395]
I can see that other agents have an ignoreurls settings, does that exist yet for this agent? I look through the code but couldn't find that.

**Comment by SergeyKleyman** [comment]
Hi @mikkeschiren. Thank you for trying the agent and providing feedback.
You are correct - at the moment the agent doesn't support this configuration setting yet. We do have an issue (#82) in the backlog to add it. I'll try to see if we can push it closer to the top of the backlog. 

In the meantime if you can change the application's source code, a possible workaround is to add the following code to your application to discard transactions based on any condition (including matching URL path pattern):
```
if (/* request URL matches IGNORE_URLS pattern */) {
    ElasticApm::getCurrentTransaction()->discard();
}
```

Of course, you or any other community member are welcome to contribute support for this or any other yet-to-be-implemented feature.

**Comment by SergeyKleyman** [comment]
I'm going to close this issue. Please watch [Configuration option: TRANSACTION_IGNORE_URLS #82](https://github.com/elastic/apm-agent-php/issues/82) if you would like to get notified when the requested feature is implemented.
