### ISSUE TITLE
Build Error w/ PHP 7.4.17 x64 

### ISSUE THREAD

**Issue by mikehenry1979-bah** [elastic/apm-agent-php#396]
I need to install the agent in Windows with a Moodle site running on PHP 7.4.17 x64 NTS and I'm getting a nmake error when trying to build a DLL.  Steps are:

x64 Native Tools Command Prompt for VS 2017
```
cd \Moodle
git clone https://github.com/Microsoft/php-sdk-binary-tools.git PHP
cd PHP
phpsdk-vc15-x64
phpsdk_buildtree phpdev
git clone https://github.com/php/php-src.git
cd php-src
git checkout PHP-7.4.17
git clone https://github.com/elastic/apm-agent-php.git source-elastic-apm-agent
mklink /j ext\elastic-apm-agent source-elastic-apm-agent\src\ext
phpsdk_deps -u
buildconf
configure --disable-all --disable-zts --enable-cli --enable-session --enable-elastic_apm
nmake

```

The mklink allows me to maintain the Git clone in php-src\source-elastic-apm-agent and makes Windows present `php-src\source-elastic-apm-agent\src\ext` as `php-src\ext\elastic-apm-agent` so that buildconf picks it up to enable in configure.  I also get the same nmake error if I actually move the folder in place instead of using the symlink method.

The nmake output with the error is:

```
Microsoft (R) Program Maintenance Utility Version 14.16.27045.0
Copyright (C) Microsoft Corporation.  All rights reserved.

SAPI.c
fopen_wrappers.c
getopt.c
internal_functions.c
main.c
mergesort.c
network.c
output.c
**main\internal_functions.c(38): error C2065: 'phpext_elastic_apm_ptr': undeclared identifier
main\internal_functions.c(36): error C2099: initializer is not a constant**
php_content_types.c
php_ini.c
php_open_temporary_file.c
php_scandir.c
php_syslog.c
php_ticks.c
php_variables.c
reentrancy.c
rfc1867.c
snprintf.c
spprintf.c
strlcat.c
strlcpy.c
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"' : return code '0x2'
Stop.

```

**Comment by SergeyKleyman** [comment]
At the moment [the agent supports Linux operating system only](https://www.elastic.co/guide/en/apm/agent/php/current/supported-technologies.html#supported-os) since it's the primary production platform for PHP applications.
I'm not familiar with Moodle but it seems [it does support Linux](https://docs.moodle.org/310/en/Installing_Moodle#Requirements).

**Comment by SergeyKleyman** [comment]
I'm going to close this issue. Please re-open it if you feel that there are some aspects of this issue that are not addressed yet.
