### ISSUE TITLE
Manual Instrumentation

### ISSUE THREAD

**Issue by philkra** [elastic/apm-agent-php#4]
Provide the PHP classes reflecting the APM event specs for users to manually instrument their codebase, leveraging the c-ext as a sender. These events are passed to the c-ext with a method e.g. `elasticapm_send_event(string $event)` and the c-ext takes care of the sending to the APM server.

**Comment by SergeyKleyman** [comment]
Public API is already implemented and documented at https://www.elastic.co/guide/en/apm/agent/php/current/public-api.html
