### ISSUE TITLE
Sending error results to Elastic APM

### ISSUE THREAD

**Issue by biswajit-landmarkgroup** [elastic/apm-agent-php#409]
For error transactions like 500/404, currently not able to record into error tab(See attachment). Also Can we have the details of error transaction.
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/63592852/116887139-948f3200-ac47-11eb-820f-857e2f4f9d51.png">

**Comment by AshanCG** [comment]
@biswajit-landmarkgroup is there any update for this , even in RUM JS we see the JS errors listed in correct section and it will very useful if we can see the HTTP 400 >=  errors under this section , instead of querying tranactions.result : *5xx* or tranactions.result : *4xx*

**Comment by lflorent** [comment]
Hello @SergeyKleyman, 

Sorry to mention you here but I think you're the most relevant to answer here. 
I parsed Github issues and Elastic forum without any clear answer on how error reporting works with this agent. 

I tried (like @biswajit-landmarkgroup @AshanCG) to leverage classic PHP errors but nothing appears in APM  error dashboard. I see the 5xx error in transactions but without any information (php error trace) about the php error.

You closed this issue https://github.com/elastic/apm-agent-php/issues/300  but I still have the same problem with the last php agent version. Or something is not clear for me ... 

Thank you in advance for your valuable support.

**Comment by RichardLagerstrom** [comment]
This reminds of a thread I posted a few months ago https://discuss.elastic.co/t/php-apm-errors-not-showing-on-kibana-dashboard/275480 

Also lacking replies..

**Comment by lflorent** [comment]
@RichardLagerstrom I saw your thread before post here. I hoped answers ... 

We have nearly the same stack if i look your docker image compared to : php 7.3 ( fpm version with nginx) +  APM agent php 1.2 (compiled from sources with my Debian 9) + APM server 7.14.0.
 The issue doesn't appear to be version related.

**Comment by RichardLagerstrom** [comment]
@lflorent I first thought I was alone with this problem as the problem appeared to have been fixed in the issue you mentioned and almost no one mentions it elsewhere. Is it a matter of misconfiguration (ie lack of docs) or just some bug - or something else (feature actually missing?). Looking forward to someone with deeper knowledge in this to get us on the right track.

**Comment by SergeyKleyman** [comment]
I apologize for the lack of response -I'll push this issue to the top of the queue to address it ASAP. It's quite possible that this feature is not implemented yet and #300 was closed by mistake. If so I will reopen it as well.

**Comment by adamtester** [comment]
Hello, I am also having the same issue, no errors are reporting but the error rate does show:

![image](https://user-images.githubusercontent.com/2249484/132058146-2d896ee9-f2ff-4d46-a8fc-db9e24e631e7.png)

Tested on Kibana 7 and just now the 8 beta.

**Comment by denwagh** [comment]
Same issue here. We just began implementing the agent for PHP (use it elsewhere, JS, etc no issues) but exact issue as above, error percentage is recorded, errors are not. Any update to this is appreciated before we open a ticket. Thanks!

**Comment by SergeyKleyman** [comment]
Hi. Thank you for opening the issue. I will need to discuss with the team if other agents create an error for transactions ending "failure signaling" HTTP status code. Does you application respond with 500 because the application's code sets the response code or does the web framework / PHP engine set the response code because there was an escaped exception and/or PHP error? if it's the latter which web framework do you use?

**Comment by nhadsall** [comment]
I was also sad to see this isn't working. PHP ARM is the main reasons we started an elastic stack.

**Comment by RichardLagerstrom** [comment]
@SergeyKleyman Maybe this project can give you all the answers. I put together a simple docker-compose to demonstrate the problem:

https://github.com/RichardLagerstrom/apm-agent-php-docker-compose

For more background there’s a more descriptive issue:

https://discuss.elastic.co/t/php-apm-errors-not-showing-on-kibana-dashboard/275480

Hope that helps.
