### ISSUE TITLE
verify_server_cert=false does not disable SSL/TLS certificate verification

### ISSUE THREAD

**Issue by RichardLagerstrom** [elastic/apm-agent-php#414]
**Describe the bug**
When disabling SSL/TLS certificate verification for communicating with APM server only verifypeer is disabled when verifyhost also should be disabled. This results in unexpected behaviour as one cannot bypass cerificate verification as intended.

**To Reproduce**
1. Use apm-agent-php release v1.0.1
2. Disable SSL/TLS certificate verification by adding 'verify_server_cert=false' into php.ini and/or pass environment variable 'ELASTIC_APM_VERIFY_SERVER_CERT=true' when starting PHP environment.

Debug log from agent confirms setting with:

_verify_server_cert configuration option is set to false: disabling SSL/TLS certificate verification for communication with APM Server._ 

**Expected behavior**
Skip SSL/TLS certificate verification and let me connect to the APM Server using the unverified certificate.

**FYI**
I have a patch to fix this problem for my use case, but I'd like to hear if there's any other work targeting this issue that I missed. Or some other approach to it.

My solution:

```shell
diff --git a/src/ext/backend_comm.c b/src/ext/backend_comm.c
index f4df122..fe13865 100644
--- a/src/ext/backend_comm.c
+++ b/src/ext/backend_comm.c
@@ -113,6 +113,7 @@ ResultCode sendEventsToApmServer( double serverTimeoutMilliseconds, const Config
         ELASTIC_APM_LOG_DEBUG( "verify_server_cert configuration option is set to false"
                                " - disabling SSL/TLS certificate verification for communication with APM Server..." );
         ELASTIC_APM_CURL_EASY_SETOPT( curl, CURLOPT_SSL_VERIFYPEER, 0L );
+        ELASTIC_APM_CURL_EASY_SETOPT( curl, CURLOPT_SSL_VERIFYHOST, 0L );
     }
```

**Comment by tobiasz-gleba** [comment]
issue still exists for agent v1.4.2
