### ISSUE TITLE
DB spans are missing subtype and action

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#422]
![image](https://user-images.githubusercontent.com/7782093/120315563-29d42380-c2e5-11eb-923d-c4ad3d233eb7.png)

**Comment by EtienneBruines** [comment]
The type is set as `db` but for some reason.

https://github.com/elastic/apm-agent-php/blob/master/src/ElasticApm/Impl/AutoInstrument/PdoAutoInstrumentation.php#L93

![Screenshot_20210608_141333](https://user-images.githubusercontent.com/3962174/121182853-c6f20780-c863-11eb-864f-38449337ebb1.png)
