### ISSUE TITLE
Need to complete OSS Process/legal stuff

### ISSUE THREAD

**Issue by lreuven** [elastic/apm-agent-php#44]
have a look [here](https://github.com/elastic/open-source/issues/135)

Follow up issue - [Add automatic verification for copyright header in source files #361](https://github.com/elastic/apm-agent-php/issues/361)

**Comment by SergeyKleyman** [comment]
[The tracking issue (APM PHP Agent OSS Checklist - elastic/open-source#135)](https://github.com/elastic/open-source/issues/135) is closed as done.
