### ISSUE TITLE
Provide data necessary for Dependencies chart

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#442]
- [x] Add `sample_rate` property to [transaction](https://github.com/elastic/apm-server/blob/v7.10.0/docs/spec/transactions/transaction.json#L26) and [span](https://github.com/elastic/apm-server/blob/v7.10.0/docs/spec/spans/span.json#L45) objects
- [x] [Propagate transaction sample rate using `tracestate`](https://github.com/elastic/apm/blob/master/specs/agents/tracing-sampling.md#propagation)

**Comment by phoenix-bjoern** [comment]
ATM it seems Kibana isn't showing Dependencies because of this missing feature (see linked issue). However, this is a major drawback for the PHP agent. So I would like to upvote this issue for faster implementation (8.0 instead of 8.1 milestone).

**Comment by GHostlyFOX** [comment]
I have server version 8.0 and agent 1.4.1 and I don't see any dependencies at all. empty
