### ISSUE TITLE
Master branch failing tests

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-php#461]
Hi @SergeyKleyman 

Now that @v1v [has fixed](https://github.com/elastic/apm-agent-php/pull/460) the previous issue with the master branch pipeline, it has [exposed a failure that appears to be happening inside the test suite itself](https://apm-ci.elastic.co/job/apm-agent-php/job/apm-agent-php-mbp/job/master/lastCompletedBuild/testReport/ElasticApmTests.UnitTests.UtilTests/AssertValidTransactionsAndSpansTest/Initializing___BuildAndTest___Matrix___PHP_VERSION____7_3___DOCKERFILE____Dockerfile____Static_check_and_Unit_Tests___testTransactionNotReachableFromRoot/).

Here is the text of the error:

```
Stacktrace

ElasticApmTests\UnitTests\UtilTests\AssertValidTransactionsAndSpansTest::testTransactionNotReachableFromRoot
Failed asserting that actual size 2 matches expected size 1.

/app/tests/ElasticApmTests/Util/TestCaseBase.php:189
/app/tests/ElasticApmTests/Util/TestCaseBase.php:257
/app/tests/ElasticApmTests/Util/TestCaseBase.php:270
/app/tests/ElasticApmTests/UnitTests/UtilTests/AssertValidTransactionsAndSpansTest.php:58
/app/tests/ElasticApmTests/UnitTests/UtilTests/AssertValidTransactionsAndSpansTest.php:187
```

Could you please take a look? Thanks. :)

**Comment by SergeyKleyman** [comment]
@cachedout Thank you for drawing my attention - I'll take a look ASAP.

**Comment by SergeyKleyman** [comment]
It doesn't seem to reproduce anymore. I wonder if it was because of the limited resources (CPU and/or memory) at the time the failed test run... Is there any way we can reproduce those conditions?

**Comment by cachedout** [comment]
I haven't seen these errors popping up recently so I am going to close this. If we do see these sort of errors come back, we can re-open this.
