### ISSUE TITLE
Cannot find a way to set server url configuration beside .ini or environment variable

### ISSUE THREAD

**Issue by filipepinhoalviere** [elastic/apm-agent-php#462]
Hello all,

I did search for this in the documentation and package code, but could not find the answer.

There should be available a way to set/override configurations after the Tracer instance is created, for example, setting the apm server url or the apm service name.

In my tests, i tried to set a new ELASTIC_APM_SERVER_URL with putenv(), then GlobalTracerHolder:::unset() to force the creation of a new Tracer instance, however, that is not working.

Is there a way to do this?

Best regards

**Comment by SergeyKleyman** [comment]
@filipepinhoalviere Is this issue is till relevant for you? If so could you please provide a little more details as to why you cannot set SERVER_URL using .ini or environment variable?

**Comment by SergeyKleyman** [comment]
Soft closing it for now - please reopen if it is still relevant.
