### ISSUE TITLE
[META 507] Stop collecting the field `http.request.socket.encrypted`

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-php#550]
APM agents should stop collecting the field `http.request.socket.encrypted` for HTTP requests.

See meta issue: https://github.com/elastic/apm/issues/507

**Comment by SergeyKleyman** [comment]
PHP Agent didn't have transaction's `context.request.socket.encrypted` collection implemented so far so there's nothing to do here. I've opened [#613 Add support for transaction's context.request.socket.remote_address ](https://github.com/elastic/apm-agent-php/issues/613) to take care of the other part of [the original comment](https://github.com/elastic/apm-server/pull/6152#issuecomment-920754402), specifically:

> ... agents ... should continue collecting request.socket.remote_address ...
