### ISSUE TITLE
apm-agent-php for arm64 architecture

### ISSUE THREAD

**Issue by nelsonflorez11** [elastic/apm-agent-php#564]
Hello team

I want to ask if the apm agent for php can be installed on arm64 architectures.

This agent
[https://github.com/elastic/apm-agent-php/releases/download/v1.3/apm-agent-php_1.3_all.deb](https://github.com/elastic/apm-agent-php/releases/download/v1.3/apm-agent-php_1.3_all.deb)

Do we have to compile something to make it work on arm64?

**Comment by marckula** [comment]
I am also curious about this.  I've installed https://github.com/elastic/apm-agent-php/releases/download/v1.3.1/apm-agent-php_1.3.1_all.deb on an was graviton t4g instance and when the extension attempts to load I see the following logs:

`Dec 12 20:10:08 bb-dev php: PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so' (tried: /opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so (/opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902//opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so.so (/usr/lib/php/20190902//opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

extension permissions are set appropriately

**Comment by nelsonflorez11** [comment]
Hello, in order to make the apm agent work on arm64 architectures it was necessary to compile it on an ec2 arm64 with the following procedure
https://www.elastic.co/guide/en/apm/agent/php/current/setup.html

subtitle: build to source

**Comment by marckula** [comment]
@nelsonflorez11 that's what I ended up doing, got it working thanks!

**Comment by firecow** [comment]
It would be awesome, if ARM64 was included in the deb and apk files :smile: :smile_cat:

**Comment by Nigma1337** [comment]
+1, installing from a deb would be way easier.

**Comment by intuibase** [comment]
Hey all
Indeed there are two problems. First is that we're not supporting ARM64 yet, second is that we have the wrong package naming.
We're rebuilding our build right now and we can consider building agent for an ARM64.

We will keep you posted soon
Pawel

**Comment by intuibase** [comment]
Hey all,

You can try building on aarch64  with latest 1.10.0 release.
Please follow https://github.com/intuibase/apm-agent-php/blob/main/DEVELOPMENT.md

**Comment by intuibase** [comment]
Improved package naming in this issue/PR: #1067

**Comment by patrikalienus** [comment]
Given how old this ticket is, it's safe to assume that Elastic won't ever provide ready-made binaries for ARM?

**Comment by intuibase** [comment]
@patrikalienus We will provide experimental build for ARM64 soon

**Comment by intuibase** [comment]
Hey all
We just released [APM agent v1.14.0](https://github.com/elastic/apm-agent-php/releases) with experimental support for ARM64. Please try it out and let us know it it works for you.
