### ISSUE TITLE
 CMS Bitrix

### ISSUE THREAD

**Issue by danilvoe** [elastic/apm-agent-php#569]
I use CMS Bitrix (installed on my own server) https://www.1c-bitrix.ru/. DB MySQL 5.7

Connected an agent, but only general transaction data is collected without any details.

Do you need to implement support for this CMS separately in the agent?
Is there a description of where to start the implementation of this CMS?

**Comment by SergeyKleyman** [comment]
@danilvoe Can you please try the latest release (v1.10.0)? It contains support for MySQLi so the agent should capture DB calls.

**Comment by SergeyKleyman** [comment]
Closing it for now - please let us know if you see that something is missing.
