### ISSUE TITLE
PHP Agent not working with Laravel

### ISSUE THREAD

**Issue by milan-dikkumburage** [elastic/apm-agent-php#586]
Hi Team,

I have access to elastic cloud account. I have a simple laravel app running .

I'm going to implement apm logs to laravel app. here's the steps i followed. 
But i still couldn't see the logs in the dashboard .

Note :- my laravel app running on the ubuntu server.
php version 7.4 
Laravel Framework 8.74.0

1.Download the APM agent 

I download apm-agent-php_1.3.1_all.deb (https://github.com/elastic/apm-agent-php/releases)

2.Install the downloaded package

dpkg -i  apm-agent-php_1.3.1_all.deb ( agent also successfully installed )

3.Configure the agent
I have added the agent configuration php ini file .
php ini file path :- /etc/php/7.4/fpm/php.ini 

elastic_apm.server_url="https://xxxxxxxxxxxxxxxxx:443"
elastic.apm.secret_token="xxxxxxxxxxx"
elastic_apm.service_name="My service"

**Comment by SergeyKleyman** [comment]
Could you please provide agent's logs (the agent writes its logs to syslog by default)? You can also [configure the agent to write to stderr](https://www.elastic.co/guide/en/apm/agent/php/current/configuration.html#configure-logging).

**Comment by SergeyKleyman** [comment]
@milan-dikkumburage I'm going to soft-close it for now - please re-open if you would like if it's still relevant.
