### ISSUE TITLE
php agent does not collect error or metrics data

### ISSUE THREAD

**Issue by nhadsall** [elastic/apm-agent-php#605]
I cannot tell if this is a bug or by design. I am getting transaction data, but neither errors nor metrics.

**Comment by willsilvano** [comment]
Same here. :(

**Comment by thewasta** [comment]
Environment? @nhadsall @willsilvano

**Comment by RichardLagerstrom** [comment]
Have a look here, same issue: https://github.com/elastic/apm-agent-php/issues/409#issuecomment-1013654982

**Comment by willsilvano** [comment]
Yes, it's the same problem reported in the issue #409 .

**Comment by GHostlyFOX** [comment]
Similar problem 

Apm-server - 7.17
Apm-agent-php - 7.17
PHP-FPM - 7.4.16
Elasticsearch - 7.1.17

**Comment by GHostlyFOX** [comment]
Similar problem

Apm-server - 8.0
Apm-agent-php - 8.0
PHP-FPM - 7.4.16
Elasticsearch - 8.0

**Comment by SergeyKleyman** [comment]
Regarding missing errors - it is fixed in #619
Regarding missing metrics - it's in the backlog (#16) but it's not implemented yet.

**Comment by willsilvano** [comment]
It's working now! Thanks!!
