### ISSUE TITLE
Add support for Opache preload

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#617]
A follow up to #394

**Comment by alexbaileyuk** [comment]
@SergeyKleyman do you know if there are plans to implement this? We're using `opcache.preload` as part of the Symfony recommendations listed here: https://symfony.com/doc/5.4/performance.html#use-the-opcache-class-preloading

It seems the related issue https://github.com/elastic/apm-agent-php/issues/740 just keeps getting pushed back further and further?

**Comment by lucaspouzac** [comment]
Hello, when I run php process with opcache in k8s environment, I get this error on starting : **Error Shared memory lock not obtained**.

If I disable opcache, application & agent start correctly.

Could be related to this problem?

Environment :
```
PHP 8.1.16 (cli) (built: Mar  1 2023 12:41:46) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.16, Copyright (c), by Zend Technologies
    
Symfony 4.4.34
```

**Comment by intuibase** [comment]
Hey @lucaspouzac 

From your description I assume it is an issue with PHP itself or with environment you're running PHP.
If everything is working correctly with agent deactivated - please create separate issue

Best regards,
Pawel

**Comment by intuibase** [comment]
Hey @alexbaileyuk 

Could you please test the latest release (https://github.com/elastic/apm-agent-php/releases/tag/v1.8.3) of the agent on your environment and confirm that #913  has fixed the problem?

Best regards
Pawel

**Comment by alexbaileyuk** [comment]
@intuibase still no luck unfortunately.

**Comment by alexbaileyuk** [comment]
Forgot to come back to this but the issue was resolved.
