### ISSUE TITLE
Configuration options: DISABLE_INSTRUMENTATIONS

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#62]
`DISABLE_INSTRUMENTATIONS` configuration option be used to control which parts of auto-instrumentation are enabled. 

Other agents:
- [Java](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-disable-instrumentations)
- [Node.js](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#disable-instrumentations)

**Comment by nojakub** [comment]
What is current status of this task? Is that possible to disable all default auto instrumentations?
