### ISSUE TITLE
[WARNING]  [Auto-Instrumentation] [TransactionForExtensionRequest.php:118] [discoverHttpRequestData] $_SERVER variable is not populated - forcing PHP engine to populate it... {"namespace":"Elastic\\Apm\\Impl\\AutoInstrument","class":"TransactionForExtensionRequest"}

### ISSUE THREAD

**Issue by A-Wat** [elastic/apm-agent-php#665]
**Describe the bug**
I have installed apm-agent-php.

The installation was performed using the instructions in the [reference](https://www.elastic.co/guide/en/apm/agent/php/current/index.html).

The data transfer to the APM server seems to be working correctly, but after a while I noticed the following log output in /var/log/messages.

Log message:
> Apr 10 04:30:31 hostname [14841]: [Elastic APM PHP Tracer] 2022-04-10 04:30:31.259919+09:00 [PID: 14841] [TID: 14841] [WARNING]  [Auto-Instrumentation] [TransactionForExtensionRequest.php:118] [discoverHttpRequestData] $_SERVER variable is not populated - forcing PHP engine to populate it... {"namespace":"Elastic\\Apm\\Impl\\AutoInstrument","class":"TransactionForExtensionRequest"}

Even with this log message output, data transfer to the APM server seems to be working.

**To Reproduce**
1. Install apm-agent-php using the reference procedure.
2. Add elastic_apm.server_url and elastic_apm.service_name to php.ini file.
3. Reload PHP-FPM.
4. Access to the page where the PHP program runs (repeated several times).
5. Check contents of /var/log/messages file.
6. A log message of WARNING is output.

**Server configuration**
- Operating system:MiracleLinux8.3
- Server:Nginx1.20.1
- PHP version:php8.0.12
- apm-agent-php version:1.4.2

**Expected behavior**
The WARNING log is not output.

I would like to know if you have any similar problems or information that might be relevant.

**Comment by keeshoekzema** [comment]
I had the same problem; Reading the source (https://github.com/elastic/apm-agent-php/blob/cd5133074321a78044e9b69aa5114b5fe52ccb6e/src/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php#L100) made me turn off `auto_globals_jit` in php.ini (as it's read on virtually every request anyway)

**Comment by A-Wat** [comment]
Thank you.
I was able to confirm that the Warning log is no longer output with the configuration change you gave me.

The cause is that "$_SERVER" is not present when apm-agent-php is running, right?

For performance, it would be best to be able to handle this with auto_globals_jit enabled, but that's not possible, is it?
