### ISSUE TITLE
PHP Opcache 'Warning Stuck count for pid'

### ISSUE THREAD

**Issue by keeshoekzema** [elastic/apm-agent-php#667]
**Describe the bug**
When enabling the PHP-agent, opcache will spam the error log with warnings: Warning Stuck count for pid 3238255

**To Reproduce**
Versions: PHP8.0.17, Apm-agent-php: 1.5

Use opcache with this config

    zend_extension = opcache.so
    opcache.interned_strings_buffer = 64
    opcache.revalidate_freq = 10
    opcache.enable_file_override = 1
    opcache.log_verbosity_level = 2

Note: log_verbosity_level should be at least 2 as that will output warnings, level 1 (default) only logs errors
Restart apache, with the PHP-APM agent enabled and you'll get lots of Warning Stuck count for pid 3238255

**Expected behavior**
No stuck pids.

**Comment by intuibase** [comment]
Hey @keeshoekzema 

Please verify if [https://github.com/elastic/apm-agent-php/releases/tag/v1.8.4](https://github.com/elastic/apm-agent-php/releases/tag/v1.8.4 release fixes issue for you. If you are still having problems after update, please reopen the issue.

Regards,
Pawel
