### ISSUE TITLE
How to have trace of all the process ?

### ISSUE THREAD

**Issue by henri9813** [elastic/apm-agent-php#678]
Hello,

I would like to have a complete trace for a request,

Taking example of this "simple" code:

```
for($i = 0; $i < 10000000; $i++) {
    echo "coucou";
}
```

In the APM, i would like to have a "for..." take 10s for example,

How could i do that ?

If i understood https://github.com/elastic/apm-agent-php/issues/641, you define the list of functions to listen ?

If it's the case, it's very "sad" and this make the agent "a bit useless" :/ 

Best regards

**Comment by SergeyKleyman** [comment]
@henri9813 https://github.com/elastic/apm-agent-php/issues/641 is already implemented so please take a look (also see https://www.elastic.co/guide/en/apm/agent/php/current/configuration-reference.html#config-profiling-inferred-spans-enabled)

**Comment by SergeyKleyman** [comment]
Closing it for now - please let u know if it's relevant.
