### ISSUE TITLE
IP Address in the ECS format

### ISSUE THREAD

**Issue by groensch24** [elastic/apm-agent-php#679]
I would like to implement the `client.ip` field of the ECS.

I was browsing through the code and was not sure where the implement this best. Could you give me recommendation if I should add a new class or add this to something existing?

**Comment by SergeyKleyman** [comment]
@groensch24 In case you are still interested in implementing it the result should go transaction's `context.request.socket.remote_address` (https://github.com/elastic/apm-server/blob/v7.0.0/docs/spec/request.json#L45C18-L46C47) and the best place to capture and store this information is probably [TransactionForExtensionRequest::beginTransaction](https://github.com/elastic/apm-agent-php/blob/main/agent/php/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php#L123)

**Comment by SergeyKleyman** [comment]
It turns out we already have an issue for this feature - https://github.com/elastic/apm-agent-php/issues/613. We are closing this issue as a duplicate.
