### ISSUE TITLE
Package Agent as .rpm for RHEL/Centos, Fedora, etc. Linux distros

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#71]
Package should:
- Install extension binary
- Install PHP part of the agent
- Update php.ini file(s) including setting `elastic_apm.bootstrap_php_part_file`

**Comment by v1v** [comment]
Very first approach to support the package generation with fpm:
- https://github.com/elastic/apm-agent-php/pull/79

**Comment by v1v** [comment]
We have agreed to iterate firstly with the debian packaging, then we will work on this particular issue.

**Comment by v1v** [comment]
RPM smoke testing package validation:
- https://github.com/elastic/apm-agent-php/pull/99

**Comment by v1v** [comment]
This has been implemented, so I'll close it now
