### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by apetrosyan1613** [elastic/apm-agent-php#713]
When we enabled elastic APM (1.5.1) agent for our laravel application running in Kubernetes the CPU usage for the one replica may reach until 1vCPU (without the agent that normal usage is 0.2-0,4 vCPU). Possibly we can tune agent configuration for decreasing the CPU load? (we tried to change the sample rate and log level, but we didn't notice any changes)

Thanks!

**Comment by Lansoweb** [comment]
Maybe it's related to [#839](https://github.com/elastic/apm-agent-php/issues/839). I'm experience similar issue.

**Comment by SergeyKleyman** [comment]
I'm going to close this issue. Please re-open it if you feel that there are some aspects of this issue that are not addressed yet.
