### ISSUE TITLE
Send only Exceptions to APM Server

### ISSUE THREAD

**Issue by abhishek1234graphs** [elastic/apm-agent-php#734]
We have successfully installed the Official PHP Agent with our Laravel Application inside our Docker container.
With our current configuration, all incoming HTTP requests are sent to the APM Server. Our requirement is to send only those requests that result in Exceptions.
Is it possible to tweak this extension's configuration to send only Transactions containing Errors to the APM Server (instead of all the requests)? Does this feature already exist? 
I understand that we can configure _log levels_ using the `log_level_syslog` option. Does this option filter requests sent to the APM server in addition to tweaking the logging capabilities?

**Comment by SergeyKleyman** [comment]
@abhishek1234graphs Agent does not have this feature but maybe you can achieve the desired effect by using tail-based sampling feature of APM Server - please see
https://www.elastic.co/guide/en/apm/guide/current/configure-tail-based-sampling.html#sampling-tail-trace-outcome-{input-type}

**Comment by SergeyKleyman** [comment]
Closing it for now - please let us know if it's still relevant.
