### ISSUE TITLE
Prevent Request too large errors

### ISSUE THREAD

**Issue by science695** [elastic/apm-agent-php#74]
In using philkra/elastic-apm-php-agent to instrument my applications, I have run into some size limits in the post to apm. I just thought I would share the conditions that have caused this error, and how I have mitigated them. It would be useful to have this be handled, or have methods to let me handle it.

1. Very large SQL queries. I put a maxlength on the sql query that gets sent in the span (truncate anything over).
2. Too many queries / spans. (Batch jobs that run for a long time and can build up quite a lot of spans) In my own auto instrumenting functions I set a flag that would let me temporarily turn off the auto instrumenting to avoid this issue. (i.e.: create span for large loop, turn off auto instrument, run large loop, turn it back on, end span)

I know the njson format works well with streaming events as they come, but is this something where it might want to chunk the events if the size is large?

**Comment by SergeyKleyman** [comment]
We are going to close it as it does not seem to be relevant to the current  agent implementation.
