### ISSUE TITLE
[umbrella] Develop a holistic approach to support OpCache related use cases

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-php#740]
Current open issues:
- [x] #306
- [ ] #394
- [x] #617
- [x] #634
- [x] #636
- [x] #651
- [x] #667
- [x] #737
- [x] #856

**Comment by farazive** [comment]
Should we add https://github.com/elastic/apm-agent-php/issues/617 to this task list as well?

**Comment by SergeyKleyman** [comment]
It seems that all previously found issues are resolved so closing it.
