### ISSUE TITLE
How to configure apm agent for multiple php sites on one machine

### ISSUE THREAD

**Issue by LHB6540** [elastic/apm-agent-php#757]
Follow this page [Configuration | APM PHP Agent Reference [1.x] | Elastic](https://www.elastic.co/guide/en/apm/agent/php/current/configuration.html)
It is easy to configure apm agent for one php site on the machine by configuring php.ini, but if I have multiple php apps on one machine, how should I differentiate the service_name of different apps

**Comment by kirby0025** [comment]
Hi,
I don't know if you figured this out but you can use the .user.ini php mecanism to override apm parameters on a per-app basis if you use FPM.
Fair warning tho, I have not figured out how to make it work for a CLI process.

**Comment by LHB6540** [comment]
> Hi, I don't know if you figured this out but you can use the .user.ini php mecanism to override apm parameters on a per-app basis if you use FPM. Fair warning tho, I have not figured out how to make it work for a CLI process.
Using .user.ini is useful to override apm parameters on a per-app basis if you use FPM.
The apm monitoring of the CLI process, which is connected by default. You can see a project named after the host in Kibana's apm list, which contains PHP's CLI process monitoring

**Comment by kirby0025** [comment]
In the apm I'm only seeing the "console" process (which is the expected thing I guess), but in the apm services it only reports under 'unknown-php-service' not the overrided value set by .user.ini.
And this is because the .user.ini is not working in cli mode. (cf https://www.php.net/manual/en/configuration.file.per-user.php)

**Comment by LHB6540** [comment]
Yes, I think all php's cli transactions are relegated to php or php-fpm on the machine. In order to better identify the CLI on each machine, in /etc/php.ini, I defined the service name as the machine name, so I saw items named after the host on the APM list
