### ISSUE TITLE
Limit tracking of Spans based on a certain time threshold (span_stack_trace_min_duration, span_frames_min_duration)

### ISSUE THREAD

**Issue by victortodoran** [elastic/apm-agent-php#762]
**Is your feature request related to a problem? Please describe.**
My transaction contains **a lot** of SQL queries. 
Most of them are quite inconsequential, but because of their high number they are polluting the trace making it useless at times.

**Describe the solution you'd like**
Discarding Spans bellow a certain time threshold seems to be available for other APM Agents (Java for example)
We would need this in the PHP Agent as well

**Describe alternatives you've considered**
n.a

**Additional context**
I'm willing to join as a contributor and implement this if the ramp up does not cost more than the implementation.

**Comment by SergeyKleyman** [comment]
Closed as duplicate of https://github.com/elastic/apm-agent-php/issues/158.
