### ISSUE TITLE
How to setup automatic capture of span trace tracking

### ISSUE THREAD

**Issue by mtanzil6** [elastic/apm-agent-php#794]
I have successfully setup the PHP APM agent on our server, and we are also able to receive transactions successfully, however there are no dependencies nor any spans traces recorded.
What could be the issue here.
![image](https://user-images.githubusercontent.com/21172083/194436136-3c2d3ba7-d5b3-4231-b5f3-a5b005673524.png)
I have tried multiple log levels such as DEBUG, INFO, TRACE but no luck.

On our server and all other endpoints uses Redis, mysql, and elasticsearch and some other libraries calls. 
PHP version is 7.3

![image](https://user-images.githubusercontent.com/21172083/194756200-800717b3-088e-47fe-aec1-3ad0fd76dee8.png)

@SergeyKleyman @apmmachine

**Comment by SergeyKleyman** [comment]
>On our server and all other endpoints uses Redis, mysql, and elasticsearch and some other libraries calls.

From the above list Elastic APM PHP Agent supports only MySQL at the moment. Please try the latest agent release and let us know if there are any issues.
We plan to add Elasticsearch client really soon. Redis client is in our backlog.

**Comment by SergeyKleyman** [comment]
We are going to close this issue. Please re-open it if you feel that there are some aspects of this issue that are not addressed yet.
