### ISSUE TITLE
How to send error stack trace?

### ISSUE THREAD

**Issue by ssi-anik** [elastic/apm-agent-php#80]
Is there any way that can be used to send an error stack trace. Usually, error traces are long enough.

**Comment by SergeyKleyman** [comment]
I'm working on adding error events (https://github.com/elastic/apm-agent-php/issues/57) which will include support for stack trace.

**Comment by ssi-anik** [comment]
I just published a package few days ago. So, will be great if the package can publish can stacktrace. for now it sends through the action

**Comment by SergeyKleyman** [comment]
@ssi-anik Could you please clarify to which package you refer?

**Comment by ssi-anik** [comment]
This one,  https://github.com/ssi-anik/elastic-apm-php
