### ISSUE TITLE
Requests pummeling apm server 

### ISSUE THREAD

**Issue by bck01215** [elastic/apm-agent-php#803]
**Describe the bug**
A recent change to [src/ElasticApm/Impl/Span.php](https://github.com/elastic/apm-agent-php/commit/2c92737d84fff5a30a9e68e844a4ab9ffee4970d#diff-4b6ccd4388d759070fd23d7f8cc68bc6f88140667dbfdf8cc67d5b61745517b1L260) is causing the apm agent to pummel the apm server with requests. While this gives more instant data for the apm server, it puts a large load on other resources. 

**To Reproduce**
Run the latest agent from main

**Expected behavior**
Fewer requests to send the same data

**Comment by estolfo** [comment]
Hi @bck01215 thanks for opening this issue. Please continue using the latest version of the agent, [1.6.1](https://github.com/elastic/apm-agent-php/releases/tag/v1.6.1), until we can get this fixed.

**Comment by firecow** [comment]
![image](https://user-images.githubusercontent.com/973602/219867998-eb4de5af-4202-4f84-9a31-dec3c805d744.png)

Guess which days, we had 1.7.1 in production, and when we downgraded to 1.6.1 again :smile:

**Comment by SergeyKleyman** [comment]
We have just released [v1.8.1](https://github.com/elastic/apm-agent-php/releases/tag/v1.8.1) that should fix this issue. Could you please try it out and let us know?

**Comment by SergeyKleyman** [comment]
I'm going to close this issue. Please re-open it if you feel that there are some aspects of this issue that are not addressed yet.

**Comment by firecow** [comment]
@SergeyKleyman The pummeling occurs if you use Laravel without an .env file.

We have solved this by adding an empty `.env` file, but it would be better if you guys actually checked for the existence of an env file, and stopped shipping a quadriliion WARNINGS.

![image](https://github.com/elastic/apm-agent-php/assets/973602/0ef3db82-ec3d-4bdb-8e13-7925ad6ae4db)
