### ISSUE TITLE
Elastic-APM service not showing errors

### ISSUE THREAD

**Issue by viktor97ops** [elastic/apm-agent-php#815]
Hi,

I have Elasticsearch 8.4.1 deployed in Kubernetes with an enabled security module in order to use APM feature.

We have a PHP application deployed in Kubernetes and we're installing the elastic-APM agent within the containers.

I'm able to see the APM services in Kibana, but for the Errors page, is not showing any errors. 

This is how my elastic-apm-custom.ini file looks like:

```
[elastic]

elastic_apm.enabled = true

;elastic_apm.api_key = "REPLACE_WITH_API_KEY"

elastic_apm.environment = "development"

elastic_apm.log_level = "TRACE"

elastic_apm.log_level_stderr = "WARNING"

elastic_apm.log_level_syslog = "TRACE"

elastic_apm.log_level_file = "ERROR"

;elastic_apm.secret_token = "REPLACE_WITH_SECRET_TOKEN"

elastic_apm.server_timeout = "10s"

elastic_apm.server_url = "http://helm-apm-server-security-apm-server.test:8200"

elastic_apm.service_name = "test"

;elastic_apm.service_version = "REPLACE_WITH_OUTPUT_FROM_git rev-parse HEAD"

elastic_apm.transaction_max_spans = 1000

elastic_apm.transaction_sample_rate = 1.0
```

Is this a known issue with the php-elastic-apm agents?

Elasticsearch, Kibana, APM, and Metricbeat is the 8.4.1 version, deployed in the EKS cluster.

**Comment by bck01215** [comment]
I have the same issue on 7.17. I've used multiple versions the APM agent

**Comment by 6fears7** [comment]
Have you looked into the [resolution to this issue](https://github.com/elastic/apm-agent-php/issues/624)?

The TL;DR is: _It seems the most natural for the agent to abide by [error_reporting()](https://www.php.net/manual/en/function.error-reporting.php) and create error event only for PHP error types included in [error_reporting()](https://www.php.net/manual/en/function.error-reporting.php)_

Additionally, I did a manual test with the following:

```
<?php
use Elastic\Apm\ElasticApm;
use Elastic\Apm\TransactionInterface;

ElasticApm::captureCurrentTransaction(
    'transtest',
    'errortest',
    function (TransactionInterface $transaction) {
        throw new Exception('Test');
    }
);
?> 
```
PHP INI was set with: 

```
display_errors = on
error_level = E_ALL
error_reporting = -1
```

![image](https://user-images.githubusercontent.com/57415489/199757146-cf397e4b-ca88-45a7-9abd-95d2a0f4e8c8.png)

**Comment by SergeyKleyman** [comment]
@viktor97ops @bck01215 Did 6fears7's [comment above](https://github.com/elastic/apm-agent-php/issues/815#issuecomment-1302248745) helped you resolve this issue?

**Comment by SergeyKleyman** [comment]
We are going to close this issue. Please re-open it if you feel that there are some aspects of this issue that are not addressed yet.
