### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by thewunder** [elastic/apm-agent-php#839]
I installed version 1.6.1 of the elastic APM agent into our new production server which runs php-fpm 8.1.2 on ubuntu 22.04 on a EC2 instance. Other than pointing it to our elastic cloud it was stock configuration. The application itself is a large mysql backed Symfony application.

Over the last several days, CPU is averaging over 80% which prior to our transition to the new server was averaging under 20%.

Reducing the transaction_sample_rate to 0.1 from 1.0 it still had high CPU usage. Checked opcache usage, and it was not full. Restarted. After disabling the APM it returned to very low CPU usage. 

![arc_cpu](https://user-images.githubusercontent.com/1265740/207931904-bee44c6b-bfdf-4b89-bff1-57b5b018f109.png)

Obviously a 200-400% performance penalty perhaps even when not tracing (though i did not test setting the sample rate to 0) makes this a no-go for production use.

Is this typical? Anything I can do to mitigate the performance issues?

**Comment by thewunder** [comment]
Update: Re-enabled and changed transaction_sample_rate to 0 and now cpu is in the 20%-50% range, so the sample rate definitely impacts performance.

**Comment by boomaker** [comment]
I've been installing a Redis for my Wordpress stack: that reduced the enormous number of mysql spans collected by the Agent.
I haven't reproduced the high CPU usage afterwards.

I've come to the conclusion that the high CPU usage might be related to the very high number of spans I previously had.

@thewunder Maybe you could give it a try? Or limit the number of spans with https://www.elastic.co/guide/en/apm/agent/php/current/configuration-reference.html#config-transaction-max-spans?

**Comment by Lansoweb** [comment]
I installed elastic apm on some projects, a front in PHP and some APIs. The front doen not use any database directly only through the APIs and the CPU went crazy for all front instances. We revert the version, which in turn disabled the elastic php agent and the CPU went down.

Today, I selected an instance and installed the agent again and the CPU immediately went up. After a few minutes, I disabled it.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/2109813/219897332-59a5f6cb-22c7-4f5e-98b4-4a00f154874c.png">

I didn't notice this issue with the APIs, but will recheck this week and try to narrow down the problem.

**Comment by Lansoweb** [comment]
I installed the agent on a new instance and disabled all instrumentations (curl,db,http-client,pdo) and the CPU went up from 10% to 30%.

Then, I enabled db and pdo and the CPU went up from 35% to 60%. Then I disabled the agent and CPU wen to 10% again.

![image](https://user-images.githubusercontent.com/2109813/220937995-243a250f-8297-44d3-8b5a-e9c2f8c3df2e.png)

**Comment by SergeyKleyman** [comment]
We have just released [v1.8.1](https://github.com/elastic/apm-agent-php/releases/tag/v1.8.1) that should fix this issue. Could you please try it out and let us know?

**Comment by Lansoweb** [comment]
I'll test it today, thanks a lot.

**Comment by Lansoweb** [comment]
Looks good ... I'll deploy to other nodes, including the ones we had to uninstall the agent. I'll reply later.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/2109813/223988072-792c3dbb-a15e-4657-92e1-74aae1906635.png">

**Comment by Lansoweb** [comment]
At 7:15, I installed the agent on 2 instances, one with 1.8.0 (blue line) and one with 1.8.1 (yellow). The CPU with 1.8.0 immediately went up. Ten minutes later I upgraded the blue to 1.8.1 and CPU went down. I believe it's fixed!

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/2109813/223999116-fd57233b-f096-49cc-a02a-0a7199bd000a.png">

**Comment by SergeyKleyman** [comment]
@Lansoweb Thank you very much for letting us know.

**Comment by SergeyKleyman** [comment]
Fixed by https://github.com/elastic/apm-agent-php/pull/877

**Comment by pjaak** [comment]
Are we sure this has been fixed? @SergeyKleyman 

I am running php containers in kubernetes. I upgraded APM agent from 1.4 to 1.8.1 and deployed at around 6:15am which you can see in the graph. The containers scaled up and CPU usage is really high.
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/45154743/229647319-a714a82b-cceb-4129-bb44-e9f32f00b608.png">

**Comment by Lansoweb** [comment]
Hello @pjaak ! I've installed the 1.8.1 agent on some project and it's ok for now. But we don't use containers.
