### ISSUE TITLE
Mention open_basedir as a limitation in PHP agent documentation

### ISSUE THREAD

**Issue by intuibase** [elastic/apm-agent-php#909]
[open_basedir](https://www.php.net/manual/en/ini.core.php#ini.open-basedir) php.ini directive is limiting the files that can be accessed by PHP to the specified directory-tree, including the file itself. 

If it is specified and agent is located outside configured path - it won't be loaded correctly

**Comment by SergeyKleyman** [comment]
We already encountered the issue with agent PHP failing to load because it is located outside [open-basedir](https://www.php.net/manual/en/ini.core.php#ini.open-basedir) - maybe we should detect it during agent startup and log a message with instructions for possible workaround?
