### ISSUE TITLE
Allowed memory size StackTraceUtil.php

### ISSUE THREAD

**Issue by GHostlyFOX** [elastic/apm-agent-php#919]
**Describe the bug**
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) in /opt/elastic/apm-agent-php/src/ElasticApm/Impl/Util/StackTraceUtil.php on line 319
<pre>[ErrorException] E_ERROR
Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) (0)
/opt/elastic/apm-agent-php/src/ElasticApm/Impl/Util/StackTraceUtil.php:319

**To Reproduce**
1. Config - default
2. The console handler for data import worked

**Comment by GHostlyFOX** [comment]
In general, after the update, big performance problems began. We will have to disable the agent for the time being because it negatively affects the operation of the system as a whole.

**Comment by Legion112** [comment]
I confirm that APM has some memory leak which grows in background daemon processing.
I am attaching a screenshot of xdebug profiling. 
![image](https://github.com/elastic/apm-agent-php/assets/20613430/d59b1400-33b1-4150-ba0d-8e5375b7a755)
<img width="1467" alt="image" src="https://github.com/elastic/apm-agent-php/assets/20613430/76b08e09-2be6-49e5-802f-bc3e254ed592">

Most memory consumed by `SeriliazationUtil.php`

**Comment by Legion112** [comment]
I suspect that many deprecation messages lead to memory leaks.
Maybe if we could disable deprecation or fix the usage of deprecation stuff we could eliminate the problem with memory leak.
But I am not sure if that depreciation is truly the reason for the memory leak.
Does the extension store all errors till the end of the process? 
<img width="1675" alt="image" src="https://github.com/elastic/apm-agent-php/assets/20613430/3cc34b94-7702-458e-9c8f-bff6b3e582c9">

**Comment by intuibase** [comment]
Hi @GHostlyFOX 
Could you try with latest release? We made optimizations around stack trace capturing.

Did you tried to workaround it with stack trace limitation option?
[https://www.elastic.co/guide/en/apm/agent/php/current/configuration-reference.html#config-stack-trace-limit](https://www.elastic.co/guide/en/apm/agent/php/current/configuration-reference.html#config-stack-trace-limit)

If it is still causing issues, please attach cachegrind files into issue or if it contains sensitive date, please let us know - we will provide a safe upload link.
