### ISSUE TITLE
Unable to load dynamic library 'elastic_apm.so'

### ISSUE THREAD

**Issue by nurhambali** [elastic/apm-agent-php#94]
hi, 

i try install apm-agent-php-0.1_preview-1.noarch.rpm and then affter install i check php module, there is an error in elastic_apm.so

![image](https://user-images.githubusercontent.com/18512905/87941834-ea825700-cac5-11ea-831e-15fabdd88b2d.png)

OS: Centos7
php: PHP 7.4.8

**Comment by SergeyKleyman** [comment]
Hi @nurhambali 

I'm sorry for misunderstanding but deployment via Linux package manager (`.rpm`, `.deb`, etc.) is in the very early stages of development and it's definitely not ready to be used. That is why it's not included in the [documentation](https://github.com/elastic/apm-agent-php/blob/master/docs/setup.asciidoc) yet. The only deployment option available at the moment is the one described at the link above.

cc @v1v

**Comment by nurhambali** [comment]
Hi @SergeyKleyman,

Does this APM support Wordpress? I really hope to document from the install agent until the config website

Tx,
hambali

**Comment by SergeyKleyman** [comment]
We didn't implement any specific support for Wordpress yet because the Agent is in early stages of development. But we consider this use case as very important and we will definitely support it.

**Comment by SergeyKleyman** [comment]
@nurhambali Do you have any objections to closing this issue? You can watch https://github.com/elastic/apm-agent-php/issues/71 that tracks Agent deployment using `.rpm` package.

**Comment by nurhambali** [comment]
@SergeyKleyman  thank you for the good information that I watch [#71 ](https://github.com/elastic/apm-agent-php/issues/71) that tracks Agent deployment using .rpm
